name: RDP
on: [workflow_dispatch]
:jobs
:build
:steps
runs-on: windows-latest
name: Download ngrok -
| :run
Invoke-WebRequest
https://bin.equinox.io/c/bNyj1mQVY4 c/ngrok-stable-windows-amd64.zip -
OutFile ngrok.zip
Expand-Archive ngrok.zip
ngrok.exe authtoken/.
YOUR_AUTH_TOKEN
name: Enable RDP -
| :run
net user kamel123
MyStrong123/add.
net localgroup
administrators kamel123 /add
Set-ItemProperty -Path
'HKLM: \System\CurrentControlSet\Con
trol\Terminal Server'
-Name
'fDeny TSConnections' -Value 0
Enable-NetFirewallRule -
"DisplayGroup "Remote Desktop
ngrok.exe tcp 3389/.
